### ISSUE TITLE
GuzzleHttp Error

### ISSUE THREAD

**Issue by plex0r** [Dwolla/dwolla-php#46]
I get this error when I try to execute one of the examples... 

Fatal error: Class 'GuzzleHttp\Client' not found in /home/daniel/daniel.com/fab/dwolla/lib/client.php on line 257

any solution?

**Comment by mach-kernel** [comment]
Did you install the Guzzle library? You can do so by changing directories
to the root of the repository and then executing `composer install`.

Try and let me know.

David Stancu

@mach-kernel <http://github.com/mach-kernel>

*Dwolla* / Developer Intern

On Feb 10, 2015, at 15:27, plex0r <notifications@github.com> wrote:

I get this error when I try to execute one of the examples...

Fatal error: Class 'GuzzleHttp\Client' not found in /home/daniel/
daniel.com/fab/dwolla/lib/client.php on line 257

any solution?

—
Reply to this email directly or view it on GitHub
<https://github.com/Dwolla/dwolla-php/issues/46>.

**Comment by plex0r** [comment]
Hi, Yes I installed the library it is under the /vendor/ directory.

**Comment by mach-kernel** [comment]
Attempt doing `composer global install guzzlehttp\guzzle` and report back as to whether or not this is an issue. It sounds to me like your `$PATH` may be improperly configured.

If this is still giving you problems after that, you can also try to:

* Make a new directory
* `composer install dwolla/dwolla-php` with 2.x version contraints
* Go into the vendor directory and copy the examples into the same directory as vendor in the new directory you created
* Try running an example, composer should autoload the classes for you.

Let me know :+1:

**Comment by mach-kernel** [comment]
Closing due to nonresponse

**Comment by punit-creolestudios** [comment]
I am getting same kind of error . 

Fatal error: Class 'GuzzleHttp\Client' not found in C:\xampp\htdocs\punit\d3\lib\client.php on line 348

Any solution ?

**Comment by manjitanaad** [comment]
Hello,

I am also getting same error.
Fatal error: Class 'GuzzleHttp\Client' not found in /home/anaadit/public_html/dwolla/lib/client.php on line 347

Please tell me installations need to install on server and how i can install.

Please help me to fix this issue.

Thanks,
Manjit
