### ISSUE TITLE
Fatal error: Class 'GuzzleHttp\Client' not found

### ISSUE THREAD

**Issue by thedhrubo** [Dwolla/dwolla-php#56]
Hi,

I was trying to use GuzzleHttp for dwolla payment.
I installed dwolla-php in my localhost, then installed guzzle through the following command 
cto@cto-pc:/opt/lampp/htdocs/dwolla$ php -r "readfile('https://getcomposer.org/installer');" | php
cto@cto-pc:/opt/lampp/htdocs/dwolla$ php composer.phar install

and finally this showed : 
Writing lock file
Generating autoload files

but after that, when i try to access : http://localhost/dwolla/examples/account.php

Then it is showing : 
Fatal error: Class 'GuzzleHttp\Client' not found in /opt/lampp/htdocs/dwolla/lib/client.php on line 261

May be this is directory path related problem that's why I attached my directory structure. Please help me. What the wrong i did?

![screenshot from 2015-05-09 18 38 48](https://cloud.githubusercontent.com/assets/12371181/7550210/b047e994-f67a-11e4-970f-92077261f39c.png)

**Comment by mach-kernel** [comment]
Hi @thedhrubo,

I'm sorry I didn't notice your message sooner. If you are using composer, you need to do `require './vendor/autoload.php'` to autoload the appropriate classes. Let me know if this is still a problem for you before I close out the issue.

**Comment by thedhrubo** [comment]
Yes please close the issue

**Comment by mach-kernel** [comment]
Thank you @thedhrubo
