### ISSUE TITLE
Can't get access token after getting the code

### ISSUE THREAD

**Issue by Nisthar** [Dwolla/dwolla-php#58]
I have 2 files.
oauth.php:

require '../vendor/autoload.php';
require 'config.php';
$config = new Config;
$OAuth = new Dwolla\OAuth();
$permissions = "Send";
$OAuth->settings->sandbox = true;
$OAuth->settings->debug = true;
$OAuth->settings->oauth_scope = $permissions;

$OAuth->settings->client_id = $config->key;
$OAuth->settings->client_secret = $config->secret;

print($OAuth->genAuthUrl($config->redirect_uri));

redirect.php:

<?php
ob_start();
session_start();

// We need the OAuth class in order to do anything
require '../vendor/autoload.php';
require 'config.php';
$config = new Config;
$OAuth = new Dwolla\OAuth();
$permissions = "Send";
$OAuth->settings->sandbox = true;
$OAuth->settings->debug = true;
$OAuth->settings->oauth_scope = $permissions;

$OAuth->settings->client_id = $config->key;
$OAuth->settings->client_secret = $config->secret;

$access_set = $OAuth->get($_GET['code'],$config->redirect_uri);

?>
problem is $access_set is empty and nothing is displayed on the page.

**Comment by lochnesh** [comment]
I apologize for the delayed response.  Would you still like help with this?

**Comment by Nisthar** [comment]
@lochnesh No. I don't need it anymore. I used your nodejs library. But i think it will be nice if you could fix it :+1:
