### ISSUE TITLE
Saving mock responses for unit tests

### ISSUE THREAD

**Issue by Vasiliskov** [Dwolla/dwolla-php#60]
Guzzle has a feature for mocking responses for unit testing purposes. We do it for some other integrations and think it might be useful to add such feature to your php library. The idea is: 
- we run unit tests once with making real requests and save the response data
- we switch the mode to using local responses and all subsequent unit tests are performed with locally saved responses to avoid spending time and bothering remote servers

I expect somebody else will also need this feature. Wanted to consult with you and find out do you need it in the main trunk or should we implement it in a fork just for our usage?

**Comment by PrplHaz4** [comment]
I've been having some trouble with unit tests and manually mocking some of the key responses (very difficult to scale)...definitely interested in seeing more, but sadly don't have a ton of time to help or anything.

It seems like mocked responses would be useful for unit testing the library itself as well as identifying unintentional breaking changes.

**Comment by mach-kernel** [comment]
Hi @Vasiliskov,

This is something that I was planning to do to `dwolla-php` but have not found the time to do. If you do have the time to do so, I would love your contribution towards the library. Let me know, I am happy to assist and dedicate some resources to help this along.

Best,

David

**Comment by Vasiliskov** [comment]
Hello,

We anyway need this feature so it will be my pleasure to contribute. I will let you know if I need some assistance. Also please let me know if you have some own vision of how it should work.

Best regards.

**Comment by Vasiliskov** [comment]
Hello @mach-kernel,

I've submitted a pull request. Please check and let me know if you want something to be changed.

Thanks.

**Comment by mach-kernel** [comment]
@Vasiliskov, this looks *awesome*. I'm going to do my final merge by the end of the week. Things are a bit busy on my end so I have a few more deliverables before I can get to this. 

Thank you so much! :+1:

**Comment by capablemonkey** [comment]
+1 This is awesome. Thanks so much for your contribution, @Vasiliskov!!

**Comment by lochnesh** [comment]
Closing issue and PR because it has been open for sometime, but was never merged to master.
