### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by sweetie85** [Dwolla/dwolla-php#62]
Hi,

I am trying to install using composer, I tried using both the below commands:

composer require dwolla/dwolla-php
composer require "dwolla/dwolla-php=2.*"

None of them work and they give a error "Library not found". Any help is appreciated. If possible can you please give detailed instructions starting from installing a composer on a ftp server.

Thanks.

**Comment by sweetie85** [comment]
Please find the attached
<img width="985" alt="screen shot 2015-10-08 at 17 47 39" src="https://cloud.githubusercontent.com/assets/404879/10365784/708f476c-6de3-11e5-92bd-8875f6fb7e0c.png">
 screenshot of the error I am getting.

**Comment by lochnesh** [comment]
Sorry for the delayed response.  Are you still having this issue?

**Comment by lochnesh** [comment]
Sorry again for the delayed response.  I'm closing this issue because I cannot recreate it on recent versions.  Please re-open if it is still an issue.

**Comment by manjitanaad** [comment]
Hello,

I am also getting same error.
Fatal error: Class 'GuzzleHttp\Client' not found in /home/anaadit/public_html/dwolla/lib/client.php on line 347

Please tell me installations need to install on server and how i can install.

Please help me to fix this issue.

Thanks,
Manjit

**Comment by dharabhatia** [comment]
Hello,

I am also getting same error.
Fatal error: Class 'GuzzleHttp\Client' not found in ../dwolla/lib/client.php on line 347

plz let me know as soon as possible. 

Please help me to fix this issue.
