### ISSUE TITLE
Cannot turn off auto withdrawal via API

### ISSUE THREAD

**Issue by AdamEsterle** [Dwolla/dwolla-php#68]
How do you turn off auto withdrawal via the API?

The docs say you can:
https://docs.dwolla.com/#enabledisable-auto-withdrawal

But the thing is, if you pass false as status, it returns immediately because of the first line in
toggleAutoWithdrawalStatus()

`if (!$status) { return self::_error("toggleAutoWithdrawalStatus() requires `\$status` parameter.\n"); }`

SOLUTION:
```
public function toggleAutoWithdrawalStatus($status, $fundingId = false, $alternate_token = false) {
        if (!isset($status)) { return self::_error("toggleAutoWithdrawalStatus() requires `\$status` parameter.\n"); }
        if ($status && !$fundingId) { return self::_error("toggleAutoWithdrawalStatus() requires `\$fundingId` parameter.\n"); }

        return self::_post('/accounts/features/auto_withdrawl',
            [
                'oauth_token' => $alternate_token ? $alternate_token : self::$settings->oauth_token,
                'enabled' => $status,
                'fundingId' => $fundingId
            ]);
    }
```

That is a quick fix though there may be a better way.

**Comment by lochnesh** [comment]
Thank you for raising this issue @AdamEsterle.  I've opened a PR to fix it.  If this proposed change is merged, you can disable auto-withdrawal by 

`toggleAutoWithdrawalStatus(false, '')`
`disableAutoWithdrawal()`

**Comment by lochnesh** [comment]
Version 2.1.8 is tagged and available in Packagist

https://packagist.org/packages/dwolla/dwolla-php
