### ISSUE TITLE
Fatal error: Class 'GuzzleHttp\Client' not found

### ISSUE THREAD

**Issue by manjitanaad** [Dwolla/dwolla-php#70]
Hello,

I am also getting same error.
Fatal error: Class 'GuzzleHttp\Client' not found in /home/anaadit/public_html/dwolla/lib/client.php on line 347

Please tell me installations need to install on server and how i can install.

Please help me to fix this issue.

Thanks,
Manjit

**Comment by lochnesh** [comment]
Did you install dwolla-php in your project using composer?  Using composer should install all required dependencies.  

```
composer require dwolla/dwolla-php
```

If you did, is `guzzlehttp` listed in your project under the `vendor` folder?

**Comment by manjitanaad** [comment]
Hello,

Thanks for your response.

I have downloaded the sample code dwolla-php-master.zip from github and uploaded to the server. After this i have created application in dwolla sanbox. I have added the Application ID, Secret , PIN , oauth_token and refresh_token in _setting.php file.
I am using this url http://anaadit.net/dwolla/examples/transactions.php.
Please tell me what installations i need to install on server and how these installations will install.
Please help to fix this issue.

Thanks,
Manjit

**Comment by dharabhatia** [comment]
Hello 
When I run command  composer require dwolla/dwolla-php I am getting following error

  - The requested package dwolla/dwolla-php No version set (parsed as 1.0.0) is satisfiable by Dwolla/dwolla-php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Plz help me out.

**Comment by lochnesh** [comment]
@manjitanaad,

Your project does not have the required dependency, GuzzleHttp.  We recommend installing dwolla-php using [composer](https://getcomposer.org/).  Composer will automatically install dwolla-php and all its dependencies.  

```
composer require dwolla/dwolla-php
```

**Comment by lochnesh** [comment]
@dharabhatia 

Which version of Composer are you using?  Does it need to be upgraded?

Does composer work correctly if you specify the version?

```
composer require dwolla/dwolla-php=2.1.8
```

**Comment by dharabhatia** [comment]
Steps I follow

1. download the composer.json
2. put the composer.json on my local folder i.e /opt/lampp/htdocs/dwolla-new
3. go to command prompt
4. Go to directory of my local folder specified above. 
5. Run the command  composer require dwolla/dwolla-php=2.1.8 
6. its generates following error 

Using version ^2.1 for dwolla/dwolla-php
 ./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package dwolla/dwolla-php No version set (parsed as 1.0.0) is satisfiable by Dwolla/dwolla-php[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content. "

7. If i run the command composer require dwolla/dwolla-php it shows the same error as above.

**Comment by dharabhatia** [comment]
whether I used the command , composer require dwolla/dwolla-php=2.1.8  or composer require dwolla/dwolla-php its generates same error.

**Comment by lochnesh** [comment]
@dharabhatia 

You do not need to download composer.json, composer will generate this file for you.

Please follow these steps instead.
1.  Navigate to your project's directory
2.  Remove composer.json, composer.lock, and the vendor folder if they exist
3.  From the command prompt run 'composer require dwolla/dwolla-php'

**Comment by dharabhatia** [comment]
Hi 
I have did the steps as you said
When I run the command it give us following 
Using version ^2.1 for dwolla/dwolla-php
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing guzzlehttp/promises (1.2.0)
    Loading from cache

  - Installing psr/http-message (1.0)
    Loading from cache

  - Installing guzzlehttp/psr7 (1.3.1)
    Loading from cache

  - Installing guzzlehttp/guzzle (6.2.1)
    Loading from cache

  - Installing dwolla/dwolla-php (2.1.8)
    Loading from cache

Writing lock file
Generating autoload files

3. It have folder under vendor guzzlehttp. 
4. then I have edited the file _setting.php in dwolla/dwolla-php. i.e update API client id , client secret and access token , refresh token. 
5. Then I have edited the file account.php and accountInst.php in dwolla/dwolla-php/examples
6. when I run the file it shows " Fatal error: Class 'GuzzleHttp\Client' not found in /opt/lampp/htdocs/dwolla-new/vendor/dwolla/dwolla-php/lib/client.php on line 347"

**Comment by lochnesh** [comment]
@dharabhatia, 

Please try copying the example code you want to run to the root directory of your project '/opt/lampp/htdocs/dwolla-new'.  

Then replace "require '../lib/account.php';" with "require_once('vendor/autoload.php');".  That will load all the dependencies that composer installed.

**Comment by dharabhatia** [comment]
@lochnesh 

Thanks a lot its works. 

One more question, if I want to upload on server I only shift the vendor folder and my example required files. Does its work like that only ? or I need to do some installation on server. 

Thanks again.

**Comment by lochnesh** [comment]
@dharabhatia 

dwolla-php requires the dependencies that composer installs.  Copying your project directory to the server is one solution.  You can also run composer on the server or as part of a build or deploy process.  Now that your project has a composer.json file you only need to run 'composer install' to get all dependencies.

**Comment by dharabhatia** [comment]
Ok thanks a lot for your response. Please let me know your skype id for future purpose if you can.

**Comment by spencerhunter** [comment]
@dharabhatia , For follow up questions, please don't hesitate to open a thread on our support forum here: https://discuss.dwolla.com/c/api-support. It looks like you were able to get everything installed okay so I'm closing out this issue.

**Comment by manjitanaad** [comment]
Thanks for the response. Actually I am not familiar with Composer. I have downloaded the master zip file and paste in my local server ( M:\xampp\htdocs\dwolla ) here is following folders examples,lib & tests. I have removed composer.json, composer.lock, Readme files etc. Please tell me steps so that i can integrate dwolla.

**Comment by dharabhatia** [comment]
@manjitanaad 

Follow the steps above I have mentioned. Remove all the directory from your folder and just hit the command    composer require dwolla/dwolla-php

1. Create directory suppose dwollaphp
2. Go to directory  location i.e dwollaphp from command prompt.
3. Hit the command composer require dwolla/dwolla-php
So you have dwolla all setup folders.

**Comment by manjitanaad** [comment]
Thanks for your quick resxpose @dharabhatia 
I did but its giving me error:-

M:\>cd xampp

M:\xampp>cd htdocs

M:\xampp\htdocs>cd dwolla

M:\xampp\htdocs\dwolla>composer require dwolla/dwolla-php
'composer' is not recognized as an internal or external command,
operable program or batch file.

M:\xampp\htdocs\dwolla>

Please help me to fix this issue.

**Comment by dharabhatia** [comment]
First of all Install composer to run composer command

php composer-setup.php --install-dir=bin --filename=composer

My suggestion for install-dir=/usr/local/bin or whatever you global directory 
For more you can refer to https://getcomposer.org/doc/00-intro.md or 
https://getcomposer.org/download/

After the successfully installation for composer then run command.

**Comment by manjitanaad** [comment]
Let me know I need to install Composer-Setup.exe file on my local server. I waiting for your response.

**Comment by manjitanaad** [comment]
I have downloaded the Composer-Setup.exe from https://getcomposer.org/download/ and tried to install but it is giving error on installation time. Please help me to fix this issue. Can you please give me your skype id so that i can talk you better.

**Comment by manjitanaad** [comment]
Thanks for your help. I have installed composer on my local server. After installation i have executed  command composer require dwolla/dwolla-php in command prompt it created vendor folder , composer.json & composer.lock files etc. Now I want to know can I process test payments from local server or I need to upload data on live server.

**Comment by dharabhatia** [comment]
You can process the payment and check the examples. Create sandbox account of Dwolla for it.

**Comment by manjitanaad** [comment]
I can process payment on local server ? This my local server url http://localhost/dwolla/send.php . But its showing nothing.
Here is code :-
-------------------------------------------------------------------------
// We need the Transactions class in order to do anything
require_once('vendor/autoload.php');
$Transactions = new Dwolla\Transactions();

/**
 * Example 1: Send $2.00 to a Dwolla ID.
 */
echo"<pre>";
print_r($Transactions->send('812-741-8051', 2.00));
echo"</pre>";

/**
 * Example 4: Get info for transaction ID '123456'.
 */
echo"<pre>";
print_r($Transactions->info('1509771'));
echo"</pre>";
--------------------------------------------------------------------------

**Comment by dharabhatia** [comment]
Hi
I have test the request of money to another dwolla user of $5 i.e in request.php its working. I am able to see in pending request on sandbox account. I hope your Dwolla Id is not correct. 
My code

require_once('../vendor/autoload.php');
$Requests = new Dwolla\Requests();

/**
 * Example 1: Request $5 from 812-740-3809
 */
print_r($Requests->create('812-740-1111', 5.00));

Replace Dwolla Id which you want to send. 
I have not testing the send method yet.

**Comment by manjitanaad** [comment]
I have tested the requests.php page with another dwolla id. but there is no pending requests & it is not showing any success message. Are you checking on live server or local server?

Please send request to Damian Wayne Industries, Dwolla ID: 812-741-8051 . This is my testing dwolla account.

Please help me to fix this issue.

**Comment by dharabhatia** [comment]
Hi 
I have send the request please check I am checking on local server only.

**Comment by manjitanaad** [comment]
Yes its showing in my pending requests. But i am unable to request for payment. when i am accessing the page its not showing error. Please help me to fix this issue

**Comment by manjitanaad** [comment]
After installation of composer require dwolla/dwolla-php if created M:\xampp\htdocs\dwolla\vendor\dwolla\dwolla-php folder. Let me know I will move all folders of this folder to root folder ( M:\xampp\htdocs\dwolla\ ) ?

**Comment by dharabhatia** [comment]
No you don't need to move all folder on root. I have just copy and paste the example folder on root of the folder and add requrie_once('vendor/authload.php') in files .

**Comment by manjitanaad** [comment]
can you please send me your setting page so that i can check that api details are correct.

**Comment by manjitanaad** [comment]
Hello,

I have setup all things on local server but unable to request for payment. when i access http://localhost/dwolla/examples/requests.php this url nothing show on this page but before installations it gives error guzzlehttp . Please help to fix this issue.

I am waiting for your kind response.

Thanks
