### ISSUE TITLE
Get Application access token

### ISSUE THREAD

**Issue by AdamEsterle** [Dwolla/dwolla-php#71]
I noticed there is not a method in V1 or V2 to be able to get the application access token.

This method I created works. Would you mind adding it?

See my Dwolla support post
https://discuss.dwolla.com/t/application-oauth-method/2798

```
public function getApplicationToken()
    {
        $params = [
            'client_id'     => self::$settings->client_id,
            'client_secret' => self::$settings->client_secret,
            'grant_type'    => 'client_credentials'
        ];

        $response = self::_post('token', $params, 'oauth/v2/', false);

        return $response['access_token'];
    }
```

**Comment by spencerhunter** [comment]
Hi @AdamEsterle.  OAuth exists on our v1 API, however tokens are shared across both v1 and v2. This SDK is used solely for API v1 and v1 does not have resources that require an application access token. 

It looks like you've [opened an issue](https://github.com/Dwolla/dwolla-swagger-php/issues/6) on dwolla-swagger-php, so we'll keep that one open for tracking and close this issue. As we progress towards adding support for OAuth on our v2 SDK we'll update the issue accordingly.
