### ISSUE TITLE
Can we charge to user using payment form submit in dwolla

### ISSUE THREAD

**Issue by manjitanaad** [Dwolla/dwolla-php#72]
Hello,

Can we charge to user using payment form submit in dwolla. Something like this url https://discuss.dwolla.com/t/help-php-developers-need-a-simple-2-page-checkout-dwolla-example/156 

Thanks

**Comment by spencerhunter** [comment]
Hi @manjitanaad , The forum thread you linked to describes redirecting a user to our off-site gateway to complete a one-time payment. This is useful for receiving payments from other users.
If using the form-submit option of the off-site gateway then there is no need to use dwolla-php. Read more on the off-site gateway [here](https://developers.dwolla.com/dev/pages/guides/offsite_gateway.html). I am closing this issue as it does not relate to using this SDK. Please create a thread on our API support forum if you have additional questions and we can address them their. https://discuss.dwolla.com/c/api-support

**Comment by manjitanaad** [comment]
Hi @spencerhunter , Thanks for your reply. I want to integrate both type of payments. In my website there is monthly plans and user will register with anyone plan and pay to website every month. After this when user login in dashboard then he will pay one time payment. So please suggest me how i can use dwolla in my website. There is one more thing when user pay  every month for monthly plan then how i will update my database. Please help me i am very confuse about dwolla payment integration php .
