### ISSUE TITLE
Get Invalid application credentials when submit payment form checkout in dwolla

### ISSUE THREAD

**Issue by manjitanaad** [Dwolla/dwolla-php#73]
Hello,

I am using payment form checkout with dwolla sandbox application credentials. When i submit form for dwolla its giving error Invalid application credentials. I have created page on my dev server. This is url of page http://anaadit.net/dwolla/testdwolla.php . Please help me to fix this issue.

Thanks,
Manjit Singh

**Comment by lochnesh** [comment]
@manjitanaad for implementation support, please post to our discussion board.  https://discuss.dwolla.com/c/api-support

Thanks!
